### ISSUE TITLE
applicable for Homemanger 2.0 protocol?

### ISSUE THREAD

**Issue by Langer75** [Knedox/venusos_sma_energy_meter#1]
Hey, thanks for the great  work. I tried to use it with Homemanager2.0 protocol. The over all Power and Energy is correct. But the values for L1, L2 and L3 are not correct decoded. Is the script applicable for Homemanager 2.0 protocol? Because of the missing Lx values it will not be used as grid meter in the graphic.
Beside your script there is another script in github https://github.com/c0deliner/venus-homemanager. The multicast decoding works fine here. But unfortunately the values will be provided more and more delayed over time (see issue #2). After 8h there is a 12sec delay.
Now I would like to have the timing of your script (no delay at all) and the decoding of venus-homemanager. May you can have a short look in to the other script to find out why the values will be more and more delayed over time
![image](https://user-images.githubusercontent.com/45699779/215354803-a60ef673-2f21-4bce-a89f-29286dd220f2.png)

May be only the offsets have to be adapted in your script. But unfortunately I did not understand the connection between OBIS objects and the offsets used in your script. May someone can help here a bit?

**Comment by Langer75** [comment]
I have changed the offsets: 
line 64: 156 instead of 164, 
line 71: 300 instead of 308, 
line 78: 444 instead of 452

**Comment by slankes** [comment]
I'd like to reopen this. Making above changes makes it work for my hm2.0 as well but I would like to understand if it's possible to detect if it's a 1.0 or 2.0 device sending the data so that we might make the code autodetect the right offsets.
